# SD212: Graph mining

# Lab 1: Sparse matrices

The objective of this lab is to understand the structure and main properties of [sparse matrices](https://en.wikipedia.org/wiki/Sparse_matrix).

## Import

In [1]:
import numpy as np

In [2]:
from scipy import sparse

## Coordinate format

In [3]:
# random matrix (dense format)
A_dense = np.random.randint(2, size = (5,10))

In [4]:
A_dense

array([[0, 0, 1, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 1, 0],
       [1, 0, 1, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1]])

In [5]:
A_coo = sparse.coo_matrix(A_dense)

In [6]:
A_coo

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 22 stored elements in COOrdinate format>

In [7]:
A_coo.shape

(5, 10)

In [8]:
A_coo.nnz

22

In [9]:
print(A_coo.row)
print(A_coo.col)
print(A_coo.data)

[0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 4 4 4 4]
[2 3 5 9 1 3 5 6 7 1 3 5 7 8 0 2 5 9 6 7 8 9]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [10]:
row = A_coo.row
col = A_coo.col
data = np.random.randint(10, size=len(A_coo.data))
shape = A_coo.shape

In [13]:
type(shape)

tuple

In [12]:
B_coo = sparse.coo_matrix((data, (row, col)), shape)

In [13]:
B_coo

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 23 stored elements in COOrdinate format>

In [14]:
B_coo.toarray()

array([[0, 1, 8, 0, 0, 0, 0, 6, 8, 0],
       [8, 0, 0, 1, 2, 0, 5, 0, 4, 0],
       [1, 0, 0, 0, 0, 2, 0, 0, 0, 2],
       [0, 6, 0, 9, 6, 3, 5, 1, 7, 0],
       [7, 0, 0, 9, 0, 0, 2, 0, 0, 0]])

In [15]:
B_coo.nnz

23

In [16]:
np.sum(B_coo.data > 0)

22

In [17]:
B_coo.eliminate_zeros()

In [18]:
B_coo

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 22 stored elements in COOrdinate format>

## To do

Complete the function below that converts a dense matrix into a sparse matrix in COO format. 

Needless to say...
* don't use `scipy`
* don't use any loop

In [19]:
class SparseCOO():
    def __init__(self, data: np.ndarray = None, row: np.ndarray = None, 
                 col: np.ndarray = None, shape: tuple = None):
        self.data = data
        self.row = row
        self.col = col
        self.shape = shape

In [20]:
def dense_to_coo(A):
    '''Convert dense matrix to sparse in COO format.
    
    Parameters
    ----------
    A : np.ndarray
        Dense matrix
        
    Returns
    -------
    A_coo : SparseCOO
        Sparse matrix in COO format.
    '''
    # to be modified
    data = A.ravel()[A.ravel()!=0]
    rows = np.argwhere(A != 0)[:,0]
    cols = np.argwhere(A != 0)[:,1]
    shape = A.shape
    A_coo = SparseCOO(data,rows,cols,shape)
    
    return A_coo

In [21]:
# test
a_coo = dense_to_coo(A_dense)
print(a_coo.row)
print(a_coo.col)
print(a_coo.data)

[0 0 0 0 1 1 1 1 1 2 2 2 3 3 3 3 3 3 3 4 4 4 4]
[1 2 7 8 0 3 4 6 8 0 5 9 1 3 4 5 6 7 8 0 3 5 6]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## CSR format

The CSR (Compressed Sparse Row) format is the more efficient for arithmetic operations (see below).

In [22]:
A_dense

array([[0, 1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 1, 1, 1, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1, 1, 0, 0, 0]])

In [23]:
A_csr = sparse.csr_matrix(A_dense)

In [24]:
A_csr

<5x10 sparse matrix of type '<class 'numpy.longlong'>'
	with 23 stored elements in Compressed Sparse Row format>

In [25]:
A_csr.shape

(5, 10)

In [26]:
A_csr.nnz

23

In [27]:
print(A_csr.indices)
print(A_csr.indptr)
print(A_csr.data)

[1 2 7 8 0 3 4 6 8 0 5 9 1 3 4 5 6 7 8 0 3 5 6]
[ 0  4  9 12 19 23]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [28]:
A_csr[3, 4]

1

In [29]:
A_csr[3]

<1x10 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [30]:
indices = A_csr.indices
indptr = A_csr.indptr
data = np.random.randint(10, size=len(A_csr.data))
shape = A_csr.shape

In [31]:
B_csr = sparse.csr_matrix((data, indices, indptr), shape)

In [32]:
B_csr

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 23 stored elements in Compressed Sparse Row format>

In [33]:
B_csr.eliminate_zeros()

In [34]:
B_csr

<5x10 sparse matrix of type '<class 'numpy.int64'>'
	with 22 stored elements in Compressed Sparse Row format>

In [35]:
# from COO format
row = [0, 0, 1, 2, 2]
col = [2, 3, 0, 1, 2]
data = np.ones(5)
A_csr = sparse.csr_matrix((data, (row, col)), shape = (3, 4))

In [36]:
A_csr.toarray()

array([[0., 0., 1., 1.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.]])

In [37]:
# equivalently
A_coo = sparse.coo_matrix((data, (row, col)), shape = (3, 4))
A_csr = sparse.csr_matrix(A_coo)

In [38]:
A_csr.toarray()

array([[0., 0., 1., 1.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.]])

## To do

Complete the functions below that converts:
* a dense matrix into a sparse matrix in CSR format,
* a sparse matrix in COO format to CSR format.

Again...
* don't use `scipy`
* don't use any loop

In [39]:
class SparseCSR():
    def __init__(self, data: np.ndarray = None, indices: np.ndarray = None, 
                 indptr: np.ndarray = None, shape: tuple = None):
        self.data = data
        self.indices = indices
        self.indptr = indptr
        self.shape = shape

In [71]:
def dense_to_csr(A):
    '''Convert dense matrix to sparse in CSR format.
    
    Parameters
    ----------
    A : np.ndarray
        Dense matrix
        
    Returns
    -------
    A_csr : SparseCSR
        Sparse matrix in CSR format.
    '''
    # to be modified
    data    = A.ravel()[A.ravel()!=0]
    indices = np.argwhere(A != 0)[:,1]
    v       =  np.sum(A !=0, axis =1)
    indptr  = np.concatenate(([0],np.cumsum(v)))
    shape   = A.shape
    A_csr   = SparseCSR(data,indices,indptr,shape)
    return A_csr

In [72]:
A_dense

array([[0, 1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 1, 1, 1, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1, 1, 0, 0, 0]])

In [73]:
# test
a_csr= dense_to_csr(A_dense)
print(a_csr.indices)
print(a_csr.indptr)
print(a_csr.data)

[1 2 7 8 0 3 4 6 8 0 5 9 1 3 4 5 6 7 8 0 3 5 6]
[ 0  4  9 12 19 23]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


# def coo_to_csr(A_coo):
    '''Convert a sparse matrix from COO to CSR format.
    
    Parameters
    ----------
    A_coo : SparseCSR
        Sparse matrix in COO format.
        
    Returns
    -------
    A_csr : SparseCSR
        Sparse matrix in CSR format.
    '''
    # to be modified
    data = A_coo.data
    ind, v = np.unique(A_coo.row, return_counts=True)
    indptr  = np.concatenate(([0],np.cumsum(v)))
    indices = A_coo.col
    shape = A_coo.shape
    A_csr = SparseCSR(data,indices,indptr,shape)
    
    return A_csr

In [75]:
# test
a_csr =coo_to_csr(a_coo)
print(a_csr.indices)
print(a_csr.indptr)
print(a_csr.data)

[1 2 7 8 0 3 4 6 8 0 5 9 1 3 4 5 6 7 8 0 3 5 6]
[ 0  4  9 12 19 23]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## CSC format

In [657]:
A_dense

array([[0, 1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 1, 1, 1, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1, 1, 0, 0, 0]])

In [658]:
A_csc = sparse.csc_matrix(A_dense)

In [659]:
A_csc

<5x10 sparse matrix of type '<class 'numpy.longlong'>'
	with 23 stored elements in Compressed Sparse Column format>

In [660]:
A_csc.shape

(5, 10)

In [661]:
A_csc.nnz

23

In [662]:
print(A_csc.indices)
print(A_csc.indptr)
print(A_csc.data)

[1 2 4 0 3 0 1 3 4 1 3 2 3 4 1 3 4 0 3 0 1 3 2]
[ 0  3  5  6  9 11 14 17 19 22 23]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## LIL format

In [663]:
A_dense

array([[0, 1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 1, 1, 1, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1, 1, 0, 0, 0]])

In [664]:
A_lil = sparse.lil_matrix(A_dense)

In [665]:
A_lil

<5x10 sparse matrix of type '<class 'numpy.longlong'>'
	with 23 stored elements in List of Lists format>

In [666]:
print(A_lil.rows)
print(A_lil.data)

[list([1, 2, 7, 8]) list([0, 3, 4, 6, 8]) list([0, 5, 9])
 list([1, 3, 4, 5, 6, 7, 8]) list([0, 3, 5, 6])]
[list([1, 1, 1, 1]) list([1, 1, 1, 1, 1]) list([1, 1, 1])
 list([1, 1, 1, 1, 1, 1, 1]) list([1, 1, 1, 1])]


In [667]:
A_lil = sparse.lil_matrix(A_csr)

## To do

What is the best format to modify an entry to a sparse matrix?

In [668]:
A_csr[0, 2] = 1
A_csr.toarray()

array([[0., 0., 1., 1.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.]])

In [669]:
A_lil[0, 2] = 1
A_lil.toarray()

array([[0., 0., 1., 1.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.]])

## Diagonal format

In [670]:
A_diag = sparse.diags(np.arange(5))

In [671]:
A_diag

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements (1 diagonals) in DIAgonal format>

In [672]:
A_diag.toarray()

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 4.]])

In [673]:
A_diag.diagonal()

array([0., 1., 2., 3., 4.])

In [674]:
A = sparse.csr_matrix(A_diag)

In [675]:
A

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

## To do

Complete the following function that returns a sparse CSR matrix with the pseudo-inverse vector on the diagonal.

**Example:** pseudo inverse of (0, 1, 2) -> (0, 1, 1/2)

**Hint:** Use the property of sparse matrices!

In [690]:
def pseudo_inverse(vector):
    '''Return a sparse matrix with pseudo-inverse on the diagonal.
    
    Parameters
    ----------
    vector : np.ndarray
        Input vector. 
        
    Returns
    -------
    A_csr : sparse.csr_matrix
        Sparse matrix in scipy CSR format.
    '''    
    # to be modified
    A_csr = sparse.csr_matrix(sparse.diags(vector))
    A_csr.data = 1/A_csr.data
    return A_csr

In [691]:
# test
print(A.toarray())
print(A.indices)
print(A.indptr)
print(A.data)

[[0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]]
[1 2 3 4]
[0 0 1 2 3 4]
[1. 2. 3. 4.]


In [692]:
# test
AA = pseudo_inverse(A.diagonal())
print(AA.toarray())
print(AA.indices)
print(AA.indptr)
print(AA.data)

[[0.         0.         0.         0.         0.        ]
 [0.         1.         0.         0.         0.        ]
 [0.         0.         0.5        0.         0.        ]
 [0.         0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.         0.25      ]]
[1 2 3 4]
[0 0 1 2 3 4]
[1.         0.5        0.33333333 0.25      ]


## Operations

Usual arithmetic operations apply to sparse matrices. The only contraint is to have a sparse matrix on the **left-hand side** of the operator.

In [693]:
A = sparse.csr_matrix(A_dense)
A.toarray()

array([[0, 1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 1, 1, 1, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1, 1, 0, 0, 0]], dtype=int64)

In [694]:
n_row, n_col = A.shape

In [695]:
A.dot(np.ones(n_col, dtype=int))

array([4, 5, 3, 7, 4], dtype=int64)

In [696]:
A.T.dot(np.ones(n_row, dtype=int))

array([3, 2, 1, 3, 2, 3, 3, 2, 3, 1], dtype=int64)

In [697]:
# observe the format of the transpose
A.T

<10x5 sparse matrix of type '<class 'numpy.longlong'>'
	with 23 stored elements in Compressed Sparse Column format>

In [698]:
A.T.dot(A)

<10x10 sparse matrix of type '<class 'numpy.longlong'>'
	with 72 stored elements in Compressed Sparse Column format>

In [699]:
A.dot(A.T)

<5x5 sparse matrix of type '<class 'numpy.longlong'>'
	with 21 stored elements in Compressed Sparse Row format>

In [700]:
A.data = np.random.choice((1,2,3,4), size = len(A.data))
A.data

array([4, 4, 3, 4, 1, 4, 4, 1, 1, 1, 1, 2, 1, 3, 4, 3, 2, 1, 4, 4, 4, 1,
       1])

In [701]:
A.toarray()

array([[0, 4, 4, 0, 0, 0, 0, 3, 4, 0],
       [1, 0, 0, 4, 4, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 2],
       [0, 1, 0, 3, 4, 3, 2, 1, 4, 0],
       [4, 0, 0, 4, 0, 1, 1, 0, 0, 0]])

In [702]:
B = A > 1

In [703]:
B.toarray()

array([[False,  True,  True, False, False, False, False,  True,  True,
        False],
       [False, False, False,  True,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False,  True,  True,  True,  True, False,  True,
        False],
       [ True, False, False,  True, False, False, False, False, False,
        False]])

In [704]:
# Explain the following warning...
B = A < 1

/home/martin/anaconda3/lib/python3.6/site-packages/scipy/sparse/compressed.py:287: SparseEfficiencyWarning: Comparing a sparse matrix with a scalar greater than zero using < is inefficient, try using >= instead.
  warn(bad_scalar_msg, SparseEfficiencyWarning)


In [705]:
B.toarray()

array([[ True, False, False,  True,  True,  True,  True, False, False,
         True],
       [False,  True,  True, False, False,  True, False,  True, False,
         True],
       [False,  True,  True,  True,  True, False,  True,  True,  True,
        False],
       [ True, False,  True, False, False, False, False, False, False,
         True],
       [False,  True,  True, False,  True, False, False,  True,  True,
         True]])

In [706]:
B_dense = np.random.randint(2, size = (5,10))
B = sparse.csr_matrix(B_dense)
B

<5x10 sparse matrix of type '<class 'numpy.longlong'>'
	with 22 stored elements in Compressed Sparse Row format>

In [707]:
2 * A + 5 * B

<5x10 sparse matrix of type '<class 'numpy.longlong'>'
	with 34 stored elements in Compressed Sparse Row format>

## To do

* Complete the following function that normalizes a sparse CSR matrix with non-negative entries so that each row sums to 1 (or to 0 if the whole row is zero). 
* Do the same for the columns. 

In [763]:
def normalize_rows(A):
    '''Normalize the rows of a CSR matrix so that all sum to 1 (or 0).
    
    Parameters
    ----------
    A : sparse.csr_matrix
        Input matrix (non-negative entries).
    
    Returns
    -------
    X_ : sparse.csr_matrix
        Normalized matrix. 
    
    '''
    # to be modified
    rowSum = pseudo_inverse(np.array(A.sum(axis=1).ravel())[0])

    return rowSum.dot(A)

# def normalize(W):
#     #Find the row scalars as a Matrix_(n,1)
#     rowSumW = sp.csr_matrix(W.sum(axis=1))
#     rowSumW.data = 1/rowSumW.data

#     #Find the diagonal matrix to scale the rows
#     rowSumW = rowSumW.transpose()
#     scaling_matrix = sp.diags(rowSumW.toarray()[0])

#     return scaling_matrix.dot(W)  

In [766]:
# test
A.toarray()

array([[0, 4, 4, 0, 0, 0, 0, 3, 4, 0],
       [1, 0, 0, 4, 4, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 2],
       [0, 1, 0, 3, 4, 3, 2, 1, 4, 0],
       [4, 0, 0, 4, 0, 1, 1, 0, 0, 0]])

In [767]:
# test
normalize_rows(A).toarray()

array([[0.        , 0.26666667, 0.26666667, 0.        , 0.        ,
        0.        , 0.        , 0.2       , 0.26666667, 0.        ],
       [0.09090909, 0.        , 0.        , 0.36363636, 0.36363636,
        0.        , 0.09090909, 0.        , 0.09090909, 0.        ],
       [0.25      , 0.        , 0.        , 0.        , 0.        ,
        0.25      , 0.        , 0.        , 0.        , 0.5       ],
       [0.        , 0.05555556, 0.        , 0.16666667, 0.22222222,
        0.16666667, 0.11111111, 0.05555556, 0.22222222, 0.        ],
       [0.4       , 0.        , 0.        , 0.4       , 0.        ,
        0.1       , 0.1       , 0.        , 0.        , 0.        ]])

In [768]:
# test
A_diag.toarray()

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 4.]])

In [770]:
# test
normalize_rows(A_diag).toarray()

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## To do

Complete the following method that returns the dot product of a sparse CSR matrix with a vector.

* No loop allowed!

In [771]:
class SparseCSR():
    def __init__(self, data: np.ndarray = None, indices: np.ndarray = None, 
                 indptr: np.ndarray = None, shape: tuple = None):
        self.data = data
        self.indices = indices
        self.indptr = indptr
        self.shape = shape
        
    def dot(self, x: np.ndarray) -> np.ndarray:
        '''Sparse-vector dot product.'''
        # to be modified
        
        return None

In [774]:
print(A.toarray())
print(A.indices)
print(A.indptr)
print(A.data)

[[0 4 4 0 0 0 0 3 4 0]
 [1 0 0 4 4 0 1 0 1 0]
 [1 0 0 0 0 1 0 0 0 2]
 [0 1 0 3 4 3 2 1 4 0]
 [4 0 0 4 0 1 1 0 0 0]]
[1 2 7 8 0 3 4 6 8 0 5 9 1 3 4 5 6 7 8 0 3 5 6]
[ 0  4  9 12 19 23]
[4 4 3 4 1 4 4 1 1 1 1 2 1 3 4 3 2 1 4 4 4 1 1]


In [776]:
a=np.array(np.ones(10))
A.dot(a)

array([15., 11.,  4., 18., 10.])

In [780]:
np.split(A.data,A.indptr[1:-1])

[array([4, 4, 3, 4]),
 array([1, 4, 4, 1, 1]),
 array([1, 1, 2]),
 array([1, 3, 4, 3, 2, 1, 4]),
 array([4, 4, 1, 1])]

In [782]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [785]:
b[np.split(A.indices,A.indptr[1:-1])]

/home/martin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


IndexError: too many indices for array

## Slicing

Sparse matrices can be sliced like numpy arrays. The CSR format is more efficient for row slicing (although column slicing is possible), while the CSC format is more efficient for column slicing.

In [ ]:
A = sparse.csr_matrix(A_dense)

In [ ]:
A[:2]

In [ ]:
A[1:4][:,2:]

In [ ]:
A[np.array([0,2,4])]

## To do 

Consider the following matrix:

In [ ]:
A = sparse.csr_matrix(np.random.randint(2, size = (20,30)))

* Extract the 10 rows of largest sums and build the corresponding matrix.

## Bonus

Complete all methods of the following CSR class.

In [ ]:
class SparseCSR():
    def __init__(self, data: np.ndarray = None, indices: np.ndarray = None, 
                 indptr: np.ndarray = None, shape: tuple = None):
        self.data = data
        self.indices = indices
        self.indptr = indptr
        self.shape = shape
        
    def dot(self, x: np.ndarray) -> np.ndarray:
        '''Sparse-vector dot product.'''
        # to be modified
        return None

    def dot_array(self, X: np.ndarray) -> np.ndarray:
        '''Sparse-array dot product.'''
        # to be modified
        return None
    
    def dot_sparse(self, X: SparseCSR) -> SparseCSR:
        '''Sparse-sparse dot product.'''
        # to be modified
        return None
    
    def add_sparse(self, X: SparseCSR) -> SparseCSR:
        '''Add a sparse matrix.'''
        # to be modified
        return None
    
    def slice_row(self, index: np.ndarray) -> SparseCSR:
        '''Slice rows of a sparse matrix.'''
        # to be modified
        return None
    
    def slice_col(self, index: np.ndarray) -> SparseCSR:
        '''Slice columns of a sparse matrix.'''
        # to be modified
        return None
    
    def eliminate_zeros(self) -> SparseCSR:
        '''Eliminate zeros of a sparse matrix.'''
        # to be modified
        return None