# Tensorflow

In [1]:
import tensorflow as tf

## Create tensor:

In [79]:
# Number (0 dimension)
t = tf.constant(1)
print(t)

tf.Tensor(1, shape=(), dtype=int32)


In [80]:
# Vector (1 dimension)
t = tf.constant([1, 2, 4])
print(t)

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [81]:
# Matrix (2 dimensions)
t = tf.constant([[1, 2], [3, 4], [5, 6]])
print(t)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [82]:
# Tensor (3 dimensions)
t = tf.constant([[[1, 2], [4, 5], [8, 9]], [[11, 12], [14, 15], [18, 19]]])
print(t)

tf.Tensor(
[[[ 1  2]
  [ 4  5]
  [ 8  9]]

 [[11 12]
  [14 15]
  [18 19]]], shape=(2, 3, 2), dtype=int32)


## Expand tensors

### Two dimensions 
Vector in form of matrix

2 shape possibilities:
- 1 x n (classic form for a list/vector in programming or the transpose of a vector $V^T$)
- n x 1 (classic form for math vector $V$)

In [46]:
res = tf.expand_dims([1, 2, 4], axis=0)
print(res)

tf.Tensor([[1 2 4]], shape=(1, 3), dtype=int32)


In [54]:
res = tf.expand_dims([1, 2, 4], axis=1)
print(res)

tf.Tensor(
[[1]
 [2]
 [4]], shape=(3, 1), dtype=int32)


### Three dimensions
Matrix in form of matrix

3 shape possibilities:
- 1 x n x m (classic form of a matrix in programming)
- n x 1 x m
- n x m x 1 (classic form of a matrix in mathematics)

In [51]:
res = tf.expand_dims([[1, 2], [4, 5], [8, 9]], axis=0)
print(res)

tf.Tensor(
[[[1 2]
  [4 5]
  [8 9]]], shape=(1, 3, 2), dtype=int32)


In [52]:
res = tf.expand_dims([[1, 2], [4, 5], [8, 9]], axis=1)
print(res)

tf.Tensor(
[[[1 2]]

 [[4 5]]

 [[8 9]]], shape=(3, 1, 2), dtype=int32)


In [53]:
res = tf.expand_dims([[1, 2], [4, 5], [8, 9]], axis=2)
print(res)

tf.Tensor(
[[[1]
  [2]]

 [[4]
  [5]]

 [[8]
  [9]]], shape=(3, 2, 1), dtype=int32)


### Four dimensions

In [71]:
res = tf.expand_dims([[[1, 2], [4, 5], [8, 9]], [[11, 12], [14, 15], [18, 19]]], axis=0)
print(res)

tf.Tensor(
[[[[ 1  2]
   [ 4  5]
   [ 8  9]]

  [[11 12]
   [14 15]
   [18 19]]]], shape=(1, 2, 3, 2), dtype=int32)


In [72]:
res = tf.expand_dims([[[1, 2], [4, 5], [8, 9]], [[11, 12], [14, 15], [18, 19]]], axis=1)
print(res)

tf.Tensor(
[[[[ 1  2]
   [ 4  5]
   [ 8  9]]]


 [[[11 12]
   [14 15]
   [18 19]]]], shape=(2, 1, 3, 2), dtype=int32)


In [73]:
res = tf.expand_dims([[[1, 2], [4, 5], [8, 9]], [[11, 12], [14, 15], [18, 19]]], axis=2)
print(res)

tf.Tensor(
[[[[ 1  2]]

  [[ 4  5]]

  [[ 8  9]]]


 [[[11 12]]

  [[14 15]]

  [[18 19]]]], shape=(2, 3, 1, 2), dtype=int32)


In [74]:
res = tf.expand_dims([[[1, 2], [4, 5], [8, 9]], [[11, 12], [14, 15], [18, 19]]], axis=3)
print(res)

tf.Tensor(
[[[[ 1]
   [ 2]]

  [[ 4]
   [ 5]]

  [[ 8]
   [ 9]]]


 [[[11]
   [12]]

  [[14]
   [15]]

  [[18]
   [19]]]], shape=(2, 3, 2, 1), dtype=int32)
