In [1]:
import numpy as np

In [2]:
A = [[0,1,0,1,1],[1,0,1,0,0],[0,1,0,1,0],[1,0,1,0,1],[1,0,0,1,0]]

In [14]:
D = np.diag(np.dot(A, np.ones(np.shape(A)[0])))

In [15]:
D

array([[3., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 2.]])

In [18]:
P = np.linalg.inv(D)@A

In [19]:
P

array([[0.        , 0.33333333, 0.        , 0.33333333, 0.33333333],
       [0.5       , 0.        , 0.5       , 0.        , 0.        ],
       [0.        , 0.5       , 0.        , 0.5       , 0.        ],
       [0.33333333, 0.        , 0.33333333, 0.        , 0.33333333],
       [0.5       , 0.        , 0.        , 0.5       , 0.        ]])

In [20]:
eigenvalues = np.linalg.eig(P)

In [21]:
eigenvalues

(array([ 1.00000000e+00, -8.33333333e-01, -5.00000000e-01,  1.27271514e-16,
         3.33333333e-01]),
 array([[ 4.47213595e-01,  3.92232270e-01,  3.92232270e-01,
         -5.00000000e-01,  1.85695338e-01],
        [ 4.47213595e-01, -5.88348405e-01, -1.96116135e-01,
         -5.00000000e-01, -5.57086015e-01],
        [ 4.47213595e-01,  5.88348405e-01, -1.96116135e-01,
          5.00000000e-01, -5.57086015e-01],
        [ 4.47213595e-01, -3.92232270e-01,  3.92232270e-01,
          5.00000000e-01,  1.85695338e-01],
        [ 4.47213595e-01, -4.80511122e-16, -7.84464541e-01,
         -3.34812691e-16,  5.57086015e-01]]))

Second exercise

In [86]:
B = np.array([[1,0,0],[1,1,0],[0,1,1],[1,1,1]])

In [87]:
B

array([[1, 0, 0],
       [1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [88]:
#B = [[1,1,0,1],[0,1,1,1],[0,0,1,1]]

In [90]:
zeros1 = np.zeros((np.shape(B)[0],np.shape(B)[0]))
zeros2 = np.zeros((np.shape(B)[1],np.shape(B)[1]))
A = np.block([[zeros1,B],[np.transpose(B),zeros2]])

In [91]:
A

array([[0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1.],
       [1., 1., 0., 1., 0., 0., 0.],
       [0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0.]])

In [92]:
D1 = np.diag(B@np.ones(np.shape(B)[1]))

In [93]:
D2 = np.diag(np.transpose(B)@np.ones(np.shape(B)[0]))

In [94]:
zeros1 = np.zeros((np.shape(D1)[0],np.shape(D2)[1]))
zeros2 = np.zeros((np.shape(D2)[0],np.shape(D1)[1]))
D = np.block([[D1,zeros1],[zeros2,D2]])

In [95]:
D

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 0., 0., 2.]])

In [109]:
P1 = np.linalg.inv(D1)@B

In [110]:
P1

array([[1.        , 0.        , 0.        ],
       [0.5       , 0.5       , 0.        ],
       [0.        , 0.5       , 0.5       ],
       [0.33333333, 0.33333333, 0.33333333]])

In [111]:
P2 = np.linalg.inv(D2)@np.transpose(B)

In [112]:
P2

array([[0.33333333, 0.33333333, 0.        , 0.33333333],
       [0.        , 0.33333333, 0.33333333, 0.33333333],
       [0.        , 0.        , 0.5       , 0.5       ]])

In [115]:
zeros1 = np.zeros((np.shape(P1)[0],np.shape(P2)[1]))
zeros2 = np.zeros((np.shape(P2)[0],np.shape(P1)[1]))
P = np.bmat([[zeros1,P1],[P2,zeros2]])

In [116]:
P

matrix([[0.        , 0.        , 0.        , 0.        , 1.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.5       ,
         0.5       , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.5       , 0.5       ],
        [0.        , 0.        , 0.        , 0.        , 0.33333333,
         0.33333333, 0.33333333],
        [0.33333333, 0.33333333, 0.        , 0.33333333, 0.        ,
         0.        , 0.        ],
        [0.        , 0.33333333, 0.33333333, 0.33333333, 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.5       , 0.5       , 0.        ,
         0.        , 0.        ]])

In [117]:
eigenvalues = np.linalg.eig(P)

In [118]:
eigenvalues[0]

array([ 1.00000000e+00, -1.00000000e+00,  6.35102732e-01, -6.35102732e-01,
        2.62424736e-01, -1.71795836e-17, -2.62424736e-01])