In [1]:
import numpy as np

In [9]:
P = np.array(
    [
        [0, 0.5, 0, 0, 0.5],
        [1 / 3, 0, 1 / 3, 0, 1 / 3],
        [0, 0.5, 0, 0.5, 0],
        [0, 0, 0.5, 0, 0.5],
        [1 / 3, 1 / 3, 0, 1 / 3, 0],
    ]
)

In [10]:
P

array([[0.        , 0.5       , 0.        , 0.        , 0.5       ],
       [0.33333333, 0.        , 0.33333333, 0.        , 0.33333333],
       [0.        , 0.5       , 0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.5       , 0.        , 0.5       ],
       [0.33333333, 0.33333333, 0.        , 0.33333333, 0.        ]])

In [39]:
T0 = np.array([0, 0, 1, 1, 0])
# T0=np.array([0,1,1,1,0])
# T0=np.array([0,1,2,4,6])

In [40]:
T = T0
for i in range(50):
    T = P @ T
    print(T)

[0.         0.33333333 0.5        0.5        0.33333333]
[0.33333333 0.27777778 0.41666667 0.41666667 0.27777778]
[0.27777778 0.34259259 0.34722222 0.34722222 0.34259259]
[0.34259259 0.32253086 0.34490741 0.34490741 0.32253086]
[0.32253086 0.33667695 0.33371914 0.33371914 0.33667695]
[0.33667695 0.33097565 0.33519805 0.33519805 0.33097565]
[0.33097565 0.33428355 0.33308685 0.33308685 0.33428355]
[0.33428355 0.33278202 0.3336852  0.3336852  0.33278202]
[0.33278202 0.33358359 0.33323361 0.33323361 0.33358359]
[0.33358359 0.33319974 0.3334086  0.3334086  0.33319974]
[0.33319974 0.33339731 0.33330417 0.33330417 0.33339731]
[0.33339731 0.3333004  0.33335074 0.33335074 0.3333004 ]
[0.3333004  0.33334948 0.33332557 0.33332557 0.33334948]
[0.33334948 0.33332515 0.33333753 0.33333753 0.33332515]
[0.33332515 0.33333739 0.33333134 0.33333134 0.33333739]
[0.33333739 0.33333129 0.33333436 0.33333436 0.33333129]
[0.33333129 0.33333435 0.33333283 0.33333283 0.33333435]
[0.33333435 0.33333282 0.333333

In [2]:
T0 = np.array([0, 1, 2, 4, 6])

In [3]:
Tinf = np.ones(5) * 2.6

In [4]:
res = np.abs(Tinf - T0)

In [5]:
res

array([2.6, 1.6, 0.6, 1.4, 3.4])

In [31]:
A = np.array([[1, -1 / 2, 0], [-1 / 2, 1, -1 / 2], [0, -1 / 3, 1]])

In [32]:
A

array([[ 1.        , -0.5       ,  0.        ],
       [-0.5       ,  1.        , -0.5       ],
       [ 0.        , -0.33333333,  1.        ]])

In [33]:
inverse = np.linalg.inv(A)

In [34]:
inverse

array([[1.42857143, 0.85714286, 0.42857143],
       [0.85714286, 1.71428571, 0.85714286],
       [0.28571429, 0.57142857, 1.28571429]])

In [36]:
inverse * 7

array([[10.,  6.,  3.],
       [ 6., 12.,  6.],
       [ 2.,  4.,  9.]])

In [35]:
np.dot(inverse, np.array([1 / 2, 0, 1 / 3]))

array([0.85714286, 0.71428571, 0.57142857])

In [37]:
np.dot(inverse, np.array([1 / 2, 0, 1 / 3])) * 7

array([6., 5., 4.])

In [1]:
# import os
# os.getcwd()